### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bronzdoc** [bronzdoc/gops#1]
- [x] Show udp ports open (closed by https://github.com/bronzdoc/gops/pull/2)
- [x] Add help flag to show info about the program (closed by https://github.com/bronzdoc/gops/pull/2)
- [x] Add flags to the program (closed by https://github.com/bronzdoc/gops/pull/2)
- [ ] Display PID/Program name dynamically of open ports
- [x] Allow user search from a range of ports eg. `gops 127.0.0.1 1 80`
